"use client";
import {useEffect,useState} from "react";
import {Plus,Save,Eye,CheckCircle2,ChevronUp,ChevronDown,Package,LayoutTemplate,Settings2,Search} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {categories,themes,productsWithClearedImages,type Product,type SiteContent,type TrendEvidence} from "@/lib/catalog";
import type {ContentState} from "@/lib/content-store";
import {contentSchema} from "@/lib/content-validation";
export function AdminEditor({initial,local,signOutUrl}:{initial:ContentState;local:boolean;signOutUrl:string}){
 const [state,setState]=useState(initial),[draft,setDraft]=useState<SiteContent>(initial.draft),[selectedId,setSelectedId]=useState(initial.draft.products[0]?.id),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[search,setSearch]=useState("");
 const dirty=JSON.stringify(draft)!==JSON.stringify(state.draft);
 const hasPending=JSON.stringify(state.draft)!==JSON.stringify(state.published);
 const publicCount=productsWithClearedImages(draft.products).length;
 const activeCount=draft.products.filter(p=>p.active).length;
 const selected=draft.products.find(p=>p.id===selectedId);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 function editProduct(change:Partial<Product>){setDraft(d=>({...d,products:d.products.map(p=>p.id===selectedId?{...p,...change}:p)}));setMessage("");}
 function editEvidence(index:number,change:Partial<TrendEvidence>){if(selected)editProduct({evidence:(selected.evidence??[]).map((e,i)=>i===index?{...e,...change}:e)});}
 function move(direction:number){setDraft(d=>{const items=[...d.products];const i=items.findIndex(p=>p.id===selectedId),next=i+direction;if(next<0||next>=items.length)return d;[items[i],items[next]]=[items[next],items[i]];return {...d,products:items};});}
 function addProduct(){const id="pick-"+crypto.randomUUID().slice(0,8);const p:Product={id,brand:"",name:"",category:"food",unit:"",description:"",image:"",url:"",tags:["간편한 한 끼"],addedAt:new Date().toISOString().slice(0,10),active:false,imageRights:"pending"};setDraft(d=>({...d,products:[p,...d.products]}));setSelectedId(id);}
 async function submit(action:"save"|"publish"){
 setError("");setMessage("");
 if(action==="save"){const valid=contentSchema.safeParse(draft);if(!valid.success){const issue=valid.error.issues[0];const index=typeof issue.path[1]==="number"?issue.path[1]:null;setError((index!==null?"상품 "+(index+1)+"의 ":"")+"입력 내용을 확인해 주세요. "+issue.message);return;}}
 setBusy(true);try{
 const response=await fetch("/api/admin/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(action==="save"?{action,revision:state.revision,content:draft}:{action,revision:state.revision})});
 const result=await response.json() as ContentState & {error?:string};if(!response.ok)throw new Error(result.error||"저장하지 못했어요.");
 setState(result);setDraft(result.draft);setMessage(action==="save"?"초안을 저장했어요. 미리보기에서 확인해 주세요.":local?"로컬 방문자 화면에 반영했어요. 인터넷에는 공개되지 않았습니다.":"방문자 화면에 반영했어요.");
 }catch(e){setError(e instanceof Error?e.message:"연결을 확인한 뒤 다시 시도해 주세요.");}finally{setBusy(false);}
 }
 return <div className="admin-shell"><header className="admin-header"><a href="/" className="brand" target="_blank" rel="noopener">요즘픽<span className="brand-dot"/></a><span className="studio-label">EDITOR’S STUDIO</span><div><a href="/" target="_blank" rel="noopener">사이트 보기</a><a href={signOutUrl} onClick={e=>{if(dirty&&!window.confirm("저장하지 않은 변경 사항이 있어요. 로그아웃할까요?"))e.preventDefault();}}>로그아웃</a></div></header>
 <main className="admin-main"><div className="admin-title"><div><p className="eyebrow blue">CURATE YOUR EVERYDAY</p><h1>다음 발견을 준비해 볼까요?</h1><p>상품과 이야기를 다듬고, 미리보기로 확인하세요.</p></div><span className="admin-status">{local?"로컬 미리보기":"운영 중"}</span></div>
 <div className="admin-flow"><span><b>01</b> 초안 편집</span><span><b>02</b> 저장·미리보기</span><span><b>03</b> {local?"로컬 화면에 반영":"방문자 화면에 반영"}</span></div>
 <div className="admin-toolbar"><span className={dirty?"unsaved":"saved"}>{dirty?"저장하지 않은 변경 사항":hasPending?"저장된 초안 · 반영 전":"저장된 내용과 방문자 화면이 같아요"}</span><div><button className="secondary-button" disabled={busy||!dirty} onClick={()=>submit("save")}><Save size={16}/>{busy?"처리 중…":"초안 저장"}</button><a className="secondary-button" href="/admin/preview" target="_blank" rel="noopener" aria-disabled={dirty||busy} onClick={e=>{if(dirty||busy)e.preventDefault();}}><Eye size={16}/>미리보기</a><button className="primary-button" disabled={busy||dirty||!hasPending} onClick={()=>submit("publish")}><CheckCircle2 size={16}/>{local?"로컬 화면에 반영":"사이트에 반영"}</button></div></div>
 <div className="admin-feedback" aria-live="polite">{error&&<p role="alert" className="error">{error}</p>}{message&&<p className="success">{message}</p>}</div>
 <Tabs defaultValue="products"><TabsList className="admin-tabs"><TabsTrigger value="products"><Package size={16}/>상품 관리</TabsTrigger><TabsTrigger value="design"><LayoutTemplate size={16}/>홈 화면 문구</TabsTrigger><TabsTrigger value="settings"><Settings2 size={16}/>연결·공개 준비</TabsTrigger></TabsList>
 <TabsContent value="products"><fieldset disabled={busy} className="admin-products"><aside className="admin-sidebar"><div className="admin-sidebar-title"><h2>상품 <span>{draft.products.length}</span></h2><button className="secondary-button" onClick={addProduct} disabled={draft.products.length>=200}><Plus size={16}/>추가</button></div><label className="admin-product-search"><Search size={16}/><input placeholder="등록한 상품 찾기" aria-label="관리할 상품 검색" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="admin-product-list">{draft.products.filter(p=>(p.name+p.brand).includes(search)).map(p=><button key={p.id} className={p.id===selectedId?"selected":""} onClick={()=>setSelectedId(p.id)}><span className="admin-product-thumb">{p.image?<img src={p.image} alt="" loading="lazy" onError={e=>e.currentTarget.style.visibility="hidden"}/>:<Package size={20}/>}</span><span><strong>{p.name||"새 상품"}</strong><small>{p.brand||"브랜드 입력 대기"} · {p.active?"표시":"숨김"}</small></span></button>)}</div></aside>
 <section className="admin-product-form">{selected?<><div className="form-title"><div><p className="eyebrow blue">PRODUCT DETAILS</p><h2>{selected.name||"새로운 발견 등록하기"}</h2></div><div className="order-buttons"><button aria-label="상품 순서 위로" onClick={()=>move(-1)} disabled={draft.products[0].id===selectedId}><ChevronUp size={20}/></button><button aria-label="상품 순서 아래로" onClick={()=>move(1)} disabled={draft.products.at(-1)?.id===selectedId}><ChevronDown size={20}/></button></div></div>
 <div className="form-grid"><label>브랜드<input value={selected.brand} maxLength={50} onChange={e=>editProduct({brand:e.target.value})} placeholder="예: 풀무원"/></label><label>카테고리<select value={selected.category} onChange={e=>editProduct({category:e.target.value as Product["category"]})}>{categories.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label className="span-2">상품명<input value={selected.name} maxLength={100} onChange={e=>editProduct({name:e.target.value})}/></label><label className="span-2">발견 제목<input aria-label="발견 제목" value={selected.hook??""} maxLength={70} onChange={e=>editProduct({hook:e.target.value})} placeholder="상품이 궁금해지는 한마디"/><small>사실에 근거한 특징을 짧게 적어 주세요. 줄바꿈은 화면 폭에 맞춰 자연스럽게 표시됩니다.</small></label><label>용량·수량·구성<input value={selected.unit} maxLength={100} onChange={e=>editProduct({unit:e.target.value})} placeholder="예: 450g · 옵션은 판매처 확인"/></label><label>등록일<input type="date" value={selected.addedAt} onChange={e=>editProduct({addedAt:e.target.value})}/></label><label className="span-2">추천 이유<textarea aria-label="추천 이유" rows={3} value={selected.description} maxLength={400} onChange={e=>editProduct({description:e.target.value})}/><small>확인한 특징을 적어 주세요. 판매 순위나 사용 후기를 임의로 만들지 않습니다.</small></label><label className="span-2">쿠팡 상품·파트너스 링크<input type="url" value={selected.url} onChange={e=>editProduct({url:e.target.value})} placeholder="https://www.coupang.com/vp/products/…"/></label><label className="span-2">상품 이미지 주소<input type="url" value={selected.image} onChange={e=>editProduct({image:e.target.value,imageRights:"pending"})} placeholder="https://…"/><small>이미지를 변경하면 사용권 확인 상태가 다시 ‘확인 전’이 됩니다.</small></label></div>
 <section className="admin-evidence"><div className="admin-evidence-heading"><h3>트렌드 출처</h3><button className="secondary-button" disabled={(selected.evidence?.length??0)>=5} onClick={()=>editProduct({evidence:[...(selected.evidence??[]),{kind:"social",sourceName:"",url:"",publishedAt:new Date().toISOString().slice(0,10),checkedAt:new Date().toISOString().slice(0,10),claim:"",scope:"product"}]})}><Plus size={15}/>출처 추가</button></div><p>최대 5개. 출처가 없으면 ‘에디터 발견’으로 표시합니다. 인기 주장에는 해당 국가·기간과 근거를 적어 주세요.</p>{(selected.evidence??[]).map((e,index)=><fieldset key={index} className="admin-evidence-item"><legend>출처 {index+1}</legend><div className="form-grid"><label>출처 종류<select aria-label={"출처 "+(index+1)+" 종류"} value={e.kind} onChange={v=>editEvidence(index,{kind:v.target.value as TrendEvidence["kind"]})}><option value="social">SNS·플랫폼 자료</option><option value="coupang">쿠팡 공식 소식</option><option value="brand">브랜드 소식</option></select></label><label>발행 기관<input aria-label={"출처 "+(index+1)+" 발행 기관"} maxLength={60} value={e.sourceName} onChange={v=>editEvidence(index,{sourceName:v.target.value})}/></label><label className="span-2">원문 링크<input aria-label={"출처 "+(index+1)+" 원문 링크"} type="url" value={e.url} onChange={v=>editEvidence(index,{url:v.target.value})}/></label><label>출처 발행일<input aria-label={"출처 "+(index+1)+" 발행일"} type="date" value={e.publishedAt} onChange={v=>editEvidence(index,{publishedAt:v.target.value})}/></label><label>직접 확인한 날짜<input aria-label={"출처 "+(index+1)+" 확인일"} type="date" value={e.checkedAt} onChange={v=>editEvidence(index,{checkedAt:v.target.value})}/></label><label className="span-2">근거가 적용되는 범위<select aria-label={"출처 "+(index+1)+" 범위"} value={e.scope} onChange={v=>editEvidence(index,{scope:v.target.value as TrendEvidence["scope"]})}><option value="product">이 상품 자체에 대한 자료</option><option value="category">브랜드·관련 제품군에 대한 자료</option></select></label><label className="span-2">확인한 내용<textarea aria-label={"출처 "+(index+1)+" 확인 내용"} rows={3} maxLength={350} value={e.claim} onChange={v=>editEvidence(index,{claim:v.target.value})}/></label></div><button className="admin-source-remove" onClick={()=>editProduct({evidence:(selected.evidence??[]).filter((_,i)=>i!==index)})}>이 출처 삭제</button></fieldset>)}<label className="admin-editor-note">요즘픽의 한마디<textarea aria-label="요즘픽의 한마디" rows={3} maxLength={300} value={selected.editorialNote??""} onChange={e=>editProduct({editorialNote:e.target.value})}/><small>운영자의 해석과 추천 의견입니다. 위의 확인된 사실과 구분되어 표시됩니다.</small></label></section>
 <div className="form-options"><p>취향 모음집</p><div>{themes.filter(t=>t!=="전체").map(t=><label key={t}><input type="checkbox" checked={selected.tags.includes(t)} onChange={e=>editProduct({tags:e.target.checked?[...selected.tags,t]:selected.tags.filter(x=>x!==t)})}/>{t}</label>)}</div><label><input type="checkbox" checked={selected.active} onChange={e=>editProduct({active:e.target.checked})}/>방문자 화면에 이 상품 표시</label><label><input type="checkbox" checked={selected.imageRights==="cleared"} onChange={e=>editProduct({imageRights:e.target.checked?"cleared":"pending"})}/>이 이미지의 공개·상업적 사용 권한 확인 완료</label></div>{!state.draft.products.some(p=>p.id===selectedId)&&<button className="secondary-button cancel-product" onClick={()=>{setDraft(d=>({...d,products:d.products.filter(p=>p.id!==selectedId)}));setSelectedId(state.draft.products[0]?.id);}}>새 상품 추가 취소</button>}<p className="admin-small">실시간 가격·재고 연결 전입니다. 가격과 평점은 화면에 표시하지 않습니다.</p></>:<p>편집할 상품을 선택해 주세요.</p>}</section></fieldset></TabsContent>
 <TabsContent value="design"><fieldset disabled={busy} className="admin-panel"><h2>첫 화면의 한마디</h2><p>줄바꿈도 그대로 표시돼요. 짧고 선명한 문구를 추천합니다.</p><label>히어로 제목<textarea aria-label="히어로 제목" value={draft.heroTitle} rows={2} maxLength={40} onChange={e=>setDraft({...draft,heroTitle:e.target.value})}/></label><label>히어로 설명<textarea aria-label="히어로 설명" value={draft.heroDescription} rows={3} maxLength={130} onChange={e=>setDraft({...draft,heroDescription:e.target.value})}/></label><label>한 끼 모음집 제목<input value={draft.themeTitle} maxLength={45} onChange={e=>setDraft({...draft,themeTitle:e.target.value})}/></label><p className="admin-small">첫 화면에는 출처 발행일이 최근인 상품 최대 3개가 표시됩니다. 방문자가 직접 선택하며 자동으로 넘어가지 않습니다.</p></fieldset></TabsContent>
 <TabsContent value="settings"><fieldset disabled={busy} className="admin-panel"><h2>공개 전에 준비할 것</h2><section className="launch-readiness" aria-labelledby="launch-status-title"><h3 id="launch-status-title">공개할 상품</h3><p className="launch-count"><strong>{activeCount}</strong>개</p><p>사진 사용권 확인 {publicCount} / {activeCount}개. 확인 전인 {activeCount-publicCount}개 사진은 공란으로 표시하며, 상품 설명·출처·쿠팡 링크는 그대로 제공합니다.</p><a className="secondary-button" href="/admin/preview?mode=public" target="_blank" rel="noopener" aria-disabled={dirty||busy} onClick={e=>{if(dirty||busy)e.preventDefault();}}><Eye size={16}/>공개 화면 미리보기</a><p className="admin-small">{dirty?"먼저 초안을 저장해 주세요. 미리보기는 저장된 내용에 공개 조건을 적용합니다.":"저장된 초안으로 사진이 공란인 공개 화면을 확인합니다. 이 버튼은 인터넷에 배포하지 않습니다."}</p></section><div className="connection-status"><span/>쿠팡 파트너스·상품 자동 연동 전</div><p>현재는 운영자가 고른 상품과 일반 쿠팡 링크를 사용합니다. 주간·월간 순위는 출처가 확보된 뒤 연결합니다.</p><label className="check-label"><input type="checkbox" checked={draft.affiliateActive} onChange={e=>setDraft({...draft,affiliateActive:e.target.checked})}/>쿠팡 파트너스 제휴 안내 표시</label><p className="admin-small">이 설정은 안내 문구만 켭니다. 각 상품에 본인의 파트너스 링크도 등록해야 수익 연결이 가능합니다.</p><ul className="launch-list"><li><strong>상품 이미지</strong><span>표시 상품 중 {draft.products.filter(p=>p.active&&p.imageRights!=="cleared").length}개 사진 공란 · 사용권 확인 후 표시</span></li><li><strong>관리자 계정</strong><span>{local?"공개 전 본인 계정 지정 필요":"허용된 운영자 계정으로 로그인됨"}</span></li><li><strong>사이트 공개</strong><span>{local?"아직 인터넷에 공개하지 않았습니다":"호스팅 설정에서 공개 상태 확인"}</span></li><li><strong>가격·재고 자동 갱신</strong><span>실제 API 사용 가능 범위 확인 후 연결</span></li></ul><p className="admin-small">{local?"현재 작업은 로컬 미리보기입니다. 사이트 공개, 유료 서비스 사용과 도메인 구매는 별도 확인 후 진행합니다.":"콘텐츠 반영은 현재 사이트에 적용됩니다. 공개 범위나 유료 서비스 변경은 별도로 확인해 주세요."}</p></fieldset></TabsContent>
 </Tabs><p className="admin-bottom-note">초안은 저장소에 보관됩니다. 미리보기는 저장된 내용을 보여주며, ‘반영’ 전까지 방문자 화면은 바뀌지 않습니다.</p>
 </main></div>;
}
